# Path to your oh-my-zsh installation.
export LC_ALL="en_US.UTF-8"
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="myusuf3"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-flow brew brew-cask mvn osx pip scala tmux vundle zsh-syntax-highlighting vagrant)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/Library/Haskell/bin:$HOME/.local/bin"

source $ZSH/oh-my-zsh.sh


# Source gvm for different go versions
if [[ -f ~/.gvm/scripts/gvm ]]; then
    source ~/.gvm/scripts/gvm
fi

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# 1pass alias for my passwords, make sure Dropbox is set up right
alias 1pass="1pass --path $HOME/Dropbox/1Password/1Password.agilekeychain"
# Run emacs without window system
alias emacs="emacs -nw"

# Colors and editor
export TERM="xterm-256color"
export EDITOR="vim"
